services:
  basket:
    container_name: "basketapi"
    restart: always
    build:
      context: ./Services/Basket/Basket.API
      dockerfile: ./Dockerfile
    networks:
      - liner
    ports:
      - "5050:80"  
  
  catalog:
    container_name: "catalogapi"
    restart: always
    build:
      context: ./Services/Catalog/Catalog.API
      dockerfile: ./Dockerfile
    networks:
      - liner
    ports:
      - "5055:80"

networks:
  liner: